development:
  sessions:
    default:
      uri: mongodb://localhost/licence_finder_development
      options:
        write:
          w: 1
        read: primary
test:
  sessions:
    default:
      uri: mongodb://localhost/licence_finder_test
      options:
        write:
          w: 1
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        write:
          w: 1
        read: primary
        retry_interval: 120
