development:
  sessions:
    default:
      database: licence_finder_development
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary
test:
  sessions:
    default:
      database: licence_finder_test
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - "<%= ENV['MONGOID_HOST'] %>:<%= ENV['MONGOID_PORT'] %>"
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      options:
        write:
          w: 1
        read: primary
        # max_retries: 30
        # retry_interval: 1
